{
 "title": "Eth Tracker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": " Panel for Transaction Details with Sender, Amount, and Timestamp",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  \"hash\", \n  \"blockNumber\", \n  \"blockTimestamp\", \n  \"sender\", \n  \"amount\", \n  \"pubkey\"\nFROM \n  \"Transactions\"\nORDER BY \n  \"blockTimestamp\" DESC\nLIMIT 100;\n"
    }
   ]
  },
  {
   "title": "Total Deposits Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  \"blockTimestamp\" AS \"time\", \n  SUM(\"amount\") AS \"Total Amount\"\nFROM \n  \"Transactions\"\nGROUP BY \n  \"blockTimestamp\"\nORDER BY \n  \"blockTimestamp\";\n"
    }
   ]
  },
  {
   "title": "Panel for Sender Address Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  \"sender\", \n  SUM(\"amount\") AS \"Total Deposited Amount\"\nFROM \n  \"Transactions\"\nGROUP BY \n  \"sender\"\nORDER BY \n  \"Total Deposited Amount\" DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Panel for Internal Transactions Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  it.\"transactionHash\", \n  it.\"blockNumber\", \n  it.\"timeStamp\", \n  it.\"from\", \n  it.\"to\", \n  it.\"value\", \n  it.\"gas\", \n  it.\"gasUsed\"\nFROM \n  \"InternalTransactions\" it\nORDER BY \n  it.\"timeStamp\" DESC\nLIMIT 100;\n"
    }
   ]
  }
 ]
}