version: '3.8'

services:
  eth-tracker:
    build: .
    container_name: eth-deposit-tracker
    environment:
      - RPC_URL=${RPC_URL}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DATABASE_URL=postgresql://postgres:${POSTGRESQL_PASSWORD}@db:5432/eth_transactions
    ports:
      - "3001:3000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: eth_transactions
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3002:3000"
    depends_on:
      - db

volumes:
  postgres-data:
  grafana-data:
